apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "http://docker-registry.jx.37.97.207.41.nip.io/danielgelling/jx-test-node:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "http://docker-registry.jx.37.97.207.41.nip.io/danielgelling/jx-test-node:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-test-node
        chartPath: charts/jx-test-node
        setValueTemplates:
          image.repository: "http://docker-registry.jx.37.97.207.41.nip.io/danielgelling/jx-test-node"
          image.tag: "{{.TAG}}"
